Resolve Error CS0121 'The call is ambiguous between the following methods or properties' by un-extension the methods which collide with the ones already supplied by the Bib3 Assembly.